version: "3.9"
services:
  # traefik:
  #   container_name: traefik
  #   image: traefik:v3.0
  #   command:
  #     #- "--log.level=DEBUG"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
  qbittorrent:
    ## Default credentials - Username: admin password: adminadmin ##
    ## Change password after install from UI --> Tools --> Options --> WebUI ##
    container_name: qbittorrent
    image: linuxserver/qbittorrent:4.6.2
    networks:
      - media-stack-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
      - WEBUI_PORT=5080
    volumes:
      - /home/reshadow/my-media-stack/configs/qbittorrent:/config
      - /home/reshadow/my-media-stack/torrent-downloads:/downloads
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.1.3
    networks:
      - media-stack-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    ports:
      - 7878:7878
    volumes:
      - /home/reshadow/my-media-stack/configs/radarr:/config
      - /home/reshadow/my-media-stack/torrent-downloads:/downloads
      - /home/reshadow/my-media-stack/torrent-downloads/movies:/movies
    restart: "unless-stopped"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:3.0.10
    networks:
      - media-stack-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /home/reshadow/my-media-stack/configs/sonarr:/config
      - /home/reshadow/my-media-stack/torrent-downloads:/downloads
      - /home/reshadow/my-media-stack/torrent-downloads/tv-series:/tv
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.10.5
    networks:
      - media-stack-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /home/reshadow/my-media-stack/configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:1.7.0
    networks:
      - media-stack-network
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Vilnius
    ports:
      - 5055:5055
    volumes:
      - /home/reshadow/my-media-stack/configs/jellyseerr:/app/config
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:10.8.13
    networks:
      - media-stack-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /home/reshadow/my-media-stack/configs/jellyfin:/config
      - /home/reshadow/my-media-stack/torrent-downloads/movies:/data/movies
      - /home/reshadow/my-media-stack/torrent-downloads/tv-series:/data/tvshows
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:1.4.0
    networks:
      - media-stack-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /home/reshadow/my-media-stack/configs/bazarr:/config
      - /home/reshadow/my-media-stack/torrent-downloads/movies:/movies #optional
      - /home/reshadow/my-media-stack/torrent-downloads/tv-series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped


networks:
  media-stack-network:
    external: true
