version: "3.9"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.10
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "8080:8080"
      
  # whoami:
  #   image: "traefik/whoami"
  #   container_name: "simple-service"
  #   labels:
  #     # - "traefik.enable=true"
  #     # - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
  #     # - "traefik.http.routers.whoami.entrypoints=web"

  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
  #     - "traefik.http.routers.whoami.entrypoints=web"
  #     - "traefik.http.services.whoami.loadbalancer.server.port=80"
  #     - "traefik.http.routers.whoami.service=whoami"

  #     - "traefik.http.routers.whoami2.rule=PathPrefix(`/whoamii`)"
  #     - "traefik.http.routers.whoami2.entrypoints=web"
  #     - "traefik.http.services.whoami2.loadbalancer.server.port=80"
  #     - "traefik.http.routers.whoami2.service=whoami2"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:3.0.10
    # ports:
    #   - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /home/reshadow/my-media-stack/configs/sonarr:/config
      - /home/reshadow/my-media-stack/torrent-downloads:/downloads
      - /home/reshadow/my-media-stack/torrent-downloads/tv-series:/tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.localhost`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.service=sonarr"
      # - "traefik.enable=true"
      # - "traefik.http.routers.sonarr.rule=PathPrefix(`/sonarr`)"
      # - "traefik.http.routers.sonarr.entrypoints=web"
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.sonarr.rule=PathPrefix(`/sonarr`)"
    #   - "traefik.http.routers.sonarr.entrypoints=web"
    # - "traefik.http.services.whoami-https-service.loadbalancer.server.port=8989"
    # - "traefik.docker.network=media-stack-network"
    # - "traefik.port=8989"
    # - "traefik.docker.network=media-stack-network"
    #   - "traefik.http.routers.sonarr.service=sonarr"
    #   - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    #   - "traefik.docker.network=media-stack-network"
    restart: unless-stopped


